# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Ubuntu Tests

on: push

jobs:
  # Run lint to check syntax.
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install scipy==1.7.3 numpy==1.21.5 numba==0.56.2 cython>=0.29.32
          python -m pip install flake8
      - name: Install package
        run: |
          python -m pip install . -v
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test-37:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-timeout scipy==1.7.3 numpy==1.21.5 numba==0.56.2 cython>=0.29.32
      - name: Install package
        run: |
          python -m pip install . -v

      - name: Run pytest
        run: python -m pytest -v --timeout=300

  test-39:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-timeout scipy==1.7.3 numpy==1.21.5 numba==0.56.2 cython>=0.29.32
      - name: Install package
        run: |
          python -m pip install . -v

      - name: Run pytest
        run: python -m pytest -v --timeout=300

  test-310:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python "3.10"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-timeout scipy==1.7.3 numpy==1.21.5 numba==0.56.2 cython>=0.29.32
      - name: Install package
        run: |
          python -m pip install . -v

      - name: Run pytest
        run: python -m pytest -v --timeout=300

  test-38:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov pytest-timeout scipy==1.7.3 numpy==1.21.5 numba==0.56.2 cython>=0.29.32
      - name: Install package
        run: |
          python -m pip install . -v

      - name: Run pytest
        run: python -m pytest --cov=CyRK -v --timeout=300
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: .coverage