# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Windows Tests

on: push

jobs:
  test-37:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest scipy==1.7.3 numpy==1.21.5 numba==0.56.2 cython==3.0.0a11
      - name: Install package
        run: |
          python -m pip install . -v

      - name: Run pytest
        run: python -m pytest

  test-38cv:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov scipy==1.7.3 numpy==1.21.5 numba==0.56.2 cython>=3.0.0a11
      - name: Install package
        run: |
          python -m pip install . -v

      - name: Run pytest
        run: python -m pytest --cov=CyRK
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: .coverage

  test-39:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest scipy==1.7.3 numpy==1.21.5 numba==0.56.2 cython==3.0.0a11
      - name: Install package
        run: |
          python -m pip install . -v

      - name: Run pytest
        run: python -m pytest

  test-310:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python "3.10"
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest scipy==1.7.3 numpy==1.21.5 numba==0.56.2 cython==3.0.0a11
      - name: Install package
        run: |
          python -m pip install . -v

      - name: Run pytest
        run: python -m pytest

  # Combine and upload coverage reports.
  coverage:
    needs: test-38cv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov scipy==1.7.3 numpy==1.21.5 numba==0.56.2 cython>=3.0.0a11 coverage
      - name: Install package
        run: |
          python -m pip install . -v
      - name: Download all artifacts
        # Downloads coverage1, coverage2, etc.
        uses: actions/download-artifact@v3
      - name: Run coverage
        run: |
          coverage combine coverage*/.coverage*
          coverage report --fail-under=50
          coverage xml
      - uses: codecov/codecov-action@v3.0.0