# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Upload to Test PyPI

on: [workflow_dispatch]

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.9'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install --upgrade build
        - name: Build sdist
          run: python -m build --sdist

        - uses: actions/upload-artifact@v3
          with:
            path: dist/*.tar.gz

#  TODO: Disabling wheels for now until [issue 9](https://github.com/jrenaud90/CyRK/issues/9) is resolved.
#  build_wheels:
#    name: Build wheels on ${{ matrix.os }} for Python ${{ matrix.pyvers }}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [windows-latest, macOS-latest, ubuntu-latest]
#        pyvers: ["3.8", "3.9", "3.10"]
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up Python ${{ matrix.pyvers }}
#        uses: actions/setup-python@v3
#        with:
#          python-version: ${{ matrix.pyvers }}
#      - name: Install Build Dependencies
#        run: |
#          python -m pip install --upgrade pip
#          python -m pip install --upgrade build
#      - name: Build package
#        run: python -m build -w
#      - name: Upload wheels
#        uses: actions/upload-artifact@v3
#        with:
#          path: dist/*.whl

  upload_all:
    name: Upload wheels to Test PyPI
#    TODO: See above
#   needs: [ build_wheels, make_sdist ]
    needs: [ make_sdist ]
    runs-on: ubuntu-latest
    # if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.TESTPYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
